version: '3.8'

services:
  postgres:
    image: 'postgres:alpine'
    container_name: 'postgres'
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_back_end_app
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres: