services:
  postgres:
    image: 'postgres:alpine'
    container_name: 'test'
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped